# Use this file as an example if you need help writing your Compose files.
# The commented-out parts may or may not be relevant to your setup.

services:
  vpn:
    build: .
    container_name: openvpn-client
    cap_add: 
      - NET_ADMIN
    devices: 
      - /dev/net/tun:/dev/net/tun
    environment:
      # - SUBNETS=192.168.10.0/24
      - HTTP_PROXY=on
      - SOCKS_PROXY=on
      # - KILL_SWITCH=off
      # - LISTEN_ON=0.0.0.0
      # - PROXY_USERNAME_SECRET=username # <-- If used, these must match the name of a
      # - PROXY_PASSWORD_SECRET=password # <-- secret (NOT the file used by the secret)
      - VPN_CONFIG_FILE=open-vpn-config.ovpn
      - VPN_AUTH_SECRET=vpn_auth_secret
    volumes: 
      - ./local:/data/vpn
    ports:
      - 1080:1080
      - 8088:8080
    secrets:
      - vpn_auth_secret

secrets:
  vpn_auth_secret:
    file: ./local/credentials.txt

